layout_spectrum: 0.703616
color:
  saturation: 0.6594982
  lightness: 0.6523297
  brandStrength: 0.4497769
  brandColors:
    - '#FFFFFF'
    - '#D2E8E5'
    - '#231F20'
    - '#485C5A'
    - '#799390'
  rhythmicContrast: 0.8422323
typography_spectrum: 0.1236559
name: MajorDomo Productions
