name: MajorDomo Productions
favicon: null
layout_spectrum: 0.12505
typography_spectrum: 0.12453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#225c82'
    - '#cce5f6'
    - '#6f8593'
    - '#8fb7d1'
  brandStrength: 0.4375
  lightness: 0.6523297
  saturation: 0.6594982
  rhythmicContrast: 0.8422323
purpose: []
